services:
  whatsapp-service:
    build: .
    container_name: whatsapp_chat_forge
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./storage/session:/usr/src/app/storage/session
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
